// artifacts/financial-frontend/src/components/customers/CustomerFormDialog.tsx
import { useEffect } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
  Select, SelectContent, SelectItem, SelectTrigger, SelectValue,
} from '@/components/ui/select';
import { useToast } from '@/hooks/use-toast';
import { createCustomer, updateCustomer } from '@/services/customers';
import { ApiError } from '@/services/api';
import type { Customer } from '@/types';

const schema = z.object({
  firstName: z.string().min(2, 'Mínimo 2 caracteres').max(100),
  lastName: z.string().min(2, 'Mínimo 2 caracteres').max(100),
  identificationType: z.enum(['CC', 'CE', 'TI', 'PASSPORT', 'NIT']),
  identificationNumber: z.string().min(5, 'Mínimo 5 caracteres').max(50),
  email: z.string().email('Correo no válido').max(150),
  birthDate: z.string().min(1, 'Fecha requerida'),
});

type FormData = z.infer<typeof schema>;

interface Props {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  customer?: Customer | null;
}

export default function CustomerFormDialog({ open, onOpenChange, customer }: Props) {
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const isEdit = !!customer;

  const {
    register,
    handleSubmit,
    setValue,
    watch,
    reset,
    formState: { errors },
  } = useForm<FormData>({
    resolver: zodResolver(schema),
    defaultValues: {
      firstName: '',
      lastName: '',
      identificationType: 'CC',
      identificationNumber: '',
      email: '',
      birthDate: '',
    },
  });

  useEffect(() => {
    if (open && customer) {
      reset({
        firstName: customer.firstName,
        lastName: customer.lastName,
        identificationType: customer.identificationType,
        identificationNumber: customer.identificationNumber,
        email: customer.email,
        birthDate: customer.birthDate,
      });
    } else if (open && !customer) {
      reset({
        firstName: '',
        lastName: '',
        identificationType: 'CC',
        identificationNumber: '',
        email: '',
        birthDate: '',
      });
    }
  }, [open, customer, reset]);

  const mutation = useMutation({
    mutationFn: (data: FormData) =>
      isEdit
        ? updateCustomer(customer!.id, data)
        : createCustomer(data),
    onSuccess: (res) => {
      toast({ title: res.message });
      queryClient.invalidateQueries({ queryKey: ['customers'] });
      onOpenChange(false);
    },
    onError: (err) => {
      if (err instanceof ApiError) {
        const detail = err.errors?.map((e) => e.message).join(' | ') || err.message;
        toast({ title: 'Error', description: detail, variant: 'destructive' });
      } else {
        toast({ title: 'Error inesperado', variant: 'destructive' });
      }
    },
  });

  const onSubmit = (data: FormData) => mutation.mutate(data);

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-lg">
        <DialogHeader>
          <DialogTitle>{isEdit ? 'Editar Cliente' : 'Nuevo Cliente'}</DialogTitle>
        </DialogHeader>

        <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-1">
              <Label htmlFor="firstName">Nombre *</Label>
              <Input id="firstName" {...register('firstName')} placeholder="Juan" />
              {errors.firstName && <p className="text-xs text-destructive">{errors.firstName.message}</p>}
            </div>
            <div className="space-y-1">
              <Label htmlFor="lastName">Apellido *</Label>
              <Input id="lastName" {...register('lastName')} placeholder="Pérez" />
              {errors.lastName && <p className="text-xs text-destructive">{errors.lastName.message}</p>}
            </div>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-1">
              <Label>Tipo de identificación *</Label>
              <Select
                value={watch('identificationType')}
                onValueChange={(v) => setValue('identificationType', v as FormData['identificationType'])}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Seleccionar..." />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="CC">CC - Cédula de Ciudadanía</SelectItem>
                  <SelectItem value="CE">CE - Cédula de Extranjería</SelectItem>
                  <SelectItem value="TI">TI - Tarjeta de Identidad</SelectItem>
                  <SelectItem value="PASSPORT">Pasaporte</SelectItem>
                  <SelectItem value="NIT">NIT</SelectItem>
                </SelectContent>
              </Select>
              {errors.identificationType && (
                <p className="text-xs text-destructive">{errors.identificationType.message}</p>
              )}
            </div>
            <div className="space-y-1">
              <Label htmlFor="identificationNumber">No. de identificación *</Label>
              <Input id="identificationNumber" {...register('identificationNumber')} placeholder="12345678" />
              {errors.identificationNumber && (
                <p className="text-xs text-destructive">{errors.identificationNumber.message}</p>
              )}
            </div>
          </div>

          <div className="space-y-1">
            <Label htmlFor="email">Correo electrónico *</Label>
            <Input id="email" type="email" {...register('email')} placeholder="juan@ejemplo.com" />
            {errors.email && <p className="text-xs text-destructive">{errors.email.message}</p>}
          </div>

          <div className="space-y-1">
            <Label htmlFor="birthDate">Fecha de nacimiento *</Label>
            <Input id="birthDate" type="date" {...register('birthDate')} />
            {errors.birthDate && <p className="text-xs text-destructive">{errors.birthDate.message}</p>}
          </div>

          <DialogFooter className="pt-2">
            <Button
              type="button"
              variant="outline"
              onClick={() => onOpenChange(false)}
              disabled={mutation.isPending}
            >
              Cancelar
            </Button>
            <Button type="submit" disabled={mutation.isPending}>
              {mutation.isPending ? 'Guardando...' : isEdit ? 'Actualizar' : 'Crear cliente'}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}

// artifacts/financial-frontend/src/app/features/customers/customer-form-dialog/customer-form-dialog.component.ts
import { Component, Inject, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { MAT_DIALOG_DATA, MatDialogModule, MatDialogRef } from '@angular/material/dialog';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { MatButtonModule } from '@angular/material/button';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { CommonModule } from '@angular/common';
import { MatSnackBar } from '@angular/material/snack-bar';
import { CustomerService } from '../../../core/services/customer.service';
import { Customer, CustomerRequest } from '../../../core/models/customer.model';

export interface CustomerFormDialogData {
  customer?: Customer;
}

@Component({
  selector: 'app-customer-form-dialog',
  standalone: true,
  imports: [
    CommonModule, ReactiveFormsModule, MatDialogModule,
    MatFormFieldModule, MatInputModule, MatSelectModule,
    MatButtonModule, MatProgressSpinnerModule,
  ],
  templateUrl: './customer-form-dialog.component.html',
})
export class CustomerFormDialogComponent implements OnInit {
  form!: FormGroup;
  loading = false;
  isEdit: boolean;

  idTypes = [
    { value: 'CC', label: 'CC - Cédula de Ciudadanía' },
    { value: 'CE', label: 'CE - Cédula de Extranjería' },
    { value: 'TI', label: 'TI - Tarjeta de Identidad' },
    { value: 'PASSPORT', label: 'Pasaporte' },
    { value: 'NIT', label: 'NIT' },
  ];

  constructor(
    private fb: FormBuilder,
    private dialogRef: MatDialogRef<CustomerFormDialogComponent>,
    @Inject(MAT_DIALOG_DATA) public data: CustomerFormDialogData,
    private customerService: CustomerService,
    private snackBar: MatSnackBar
  ) {
    this.isEdit = !!data?.customer;
  }

  ngOnInit(): void {
    const c = this.data?.customer;
    this.form = this.fb.group({
      firstName: [c?.firstName ?? '', [Validators.required, Validators.minLength(2), Validators.maxLength(100)]],
      lastName: [c?.lastName ?? '', [Validators.required, Validators.minLength(2), Validators.maxLength(100)]],
      identificationType: [c?.identificationType ?? 'CC', Validators.required],
      identificationNumber: [c?.identificationNumber ?? '', [Validators.required, Validators.minLength(5), Validators.maxLength(50)]],
      email: [c?.email ?? '', [Validators.required, Validators.email, Validators.maxLength(150)]],
      birthDate: [c?.birthDate ?? '', Validators.required],
    });
  }

  getError(field: string): string {
    const control = this.form.get(field);
    if (!control?.errors || !control.touched) return '';
    if (control.errors['required']) return 'Campo obligatorio';
    if (control.errors['email']) return 'Correo no válido';
    if (control.errors['minlength']) return `Mínimo ${control.errors['minlength'].requiredLength} caracteres`;
    if (control.errors['maxlength']) return `Máximo ${control.errors['maxlength'].requiredLength} caracteres`;
    return 'Valor no válido';
  }

  onSubmit(): void {
    if (this.form.invalid) {
      this.form.markAllAsTouched();
      return;
    }
    this.loading = true;
    const data: CustomerRequest = this.form.value;
    const op$ = this.isEdit
      ? this.customerService.update(this.data.customer!.id, data)
      : this.customerService.create(data);

    op$.subscribe({
      next: (res) => {
        this.snackBar.open(res.message, 'Cerrar', { duration: 3000 });
        this.dialogRef.close(true);
      },
      error: (err: Error) => {
        this.loading = false;
        this.snackBar.open(err.message, 'Cerrar', { duration: 5000, panelClass: 'snack-error' });
      },
    });
  }

  onCancel(): void {
    this.dialogRef.close(false);
  }
}

<h2 mat-dialog-title>{{ isEdit ? 'Editar Cliente' : 'Nuevo Cliente' }}</h2>

<mat-dialog-content>
  <form [formGroup]="form" class="dialog-form">

    <div class="form-row">
      <mat-form-field appearance="outline">
        <mat-label>Nombre *</mat-label>
        <input matInput formControlName="firstName" placeholder="Juan">
        <mat-error>{{ getError('firstName') }}</mat-error>
      </mat-form-field>

      <mat-form-field appearance="outline">
        <mat-label>Apellido *</mat-label>
        <input matInput formControlName="lastName" placeholder="Pérez">
        <mat-error>{{ getError('lastName') }}</mat-error>
      </mat-form-field>
    </div>

    <div class="form-row">
      <mat-form-field appearance="outline">
        <mat-label>Tipo de identificación *</mat-label>
        <mat-select formControlName="identificationType">
          @for (t of idTypes; track t.value) {
            <mat-option [value]="t.value">{{ t.label }}</mat-option>
          }
        </mat-select>
        <mat-error>{{ getError('identificationType') }}</mat-error>
      </mat-form-field>

      <mat-form-field appearance="outline">
        <mat-label>No. de identificación *</mat-label>
        <input matInput formControlName="identificationNumber" placeholder="12345678">
        <mat-error>{{ getError('identificationNumber') }}</mat-error>
      </mat-form-field>
    </div>

    <mat-form-field appearance="outline">
      <mat-label>Correo electrónico *</mat-label>
      <input matInput type="email" formControlName="email" placeholder="juan@ejemplo.com">
      <mat-error>{{ getError('email') }}</mat-error>
    </mat-form-field>

    <mat-form-field appearance="outline">
      <mat-label>Fecha de nacimiento *</mat-label>
      <input matInput type="date" formControlName="birthDate">
      <mat-error>{{ getError('birthDate') }}</mat-error>
    </mat-form-field>

  </form>
</mat-dialog-content>

<mat-dialog-actions align="end">
  <button mat-button (click)="onCancel()" [disabled]="loading">Cancelar</button>
  <button mat-flat-button color="primary" (click)="onSubmit()" [disabled]="loading">
    @if (loading) {
      <mat-spinner diameter="16" style="display:inline-block;margin-right:8px"></mat-spinner>
    }
    {{ loading ? 'Guardando...' : (isEdit ? 'Actualizar' : 'Crear cliente') }}
  </button>
</mat-dialog-actions>
